services:
  # Nginx Service
  nginx:
    build: ./.docker/nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/var/www
    depends_on:
      - node
      - php
    networks:
      - app-network

  # PHP Service (Laravel)
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    user: "${UID}:${GID}"
    volumes:
      - ./:/var/www
      - ./.docker/php/development.ini:/usr/local/etc/php/conf.d/development.ini
    command: php-fpm
    environment:
      # Laravelが利用する環境変数を設定
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network
    depends_on:
      - db

  # Laravel Queue Worker Service
  queue:
      build:
          context: .
          dockerfile: ./.docker/php/Dockerfile # php サービスと同じ Dockerfile を使用
      user: "${UID}:${GID}"
      volumes:
          - ./:/var/www
          - ./.docker/php/development.ini:/usr/local/etc/php/conf.d/development.ini
      command: sh -c "php /var/www/artisan queue:work --sleep=3 --tries=3"
      environment:
          # php サービスと同様の環境変数を設定
          - DB_CONNECTION=${DB_CONNECTION}
          - DB_HOST=${DB_HOST}
          - DB_PORT=${DB_PORT}
          - DB_DATABASE=${DB_DATABASE}
          - DB_USERNAME=${DB_USERNAME}
          - DB_PASSWORD=${DB_PASSWORD}
      restart: always # ワーカーが何らかの理由で停止した場合に再起動
      networks:
          - app-network
      depends_on:
          - db

  # PostgreSQL + PostGIS Service
  db:
    image: postgis/postgis:16-3.4  # PostGIS対応の公式イメージ
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data # 名前付きボリュームでデータを永続化
    networks:
      - app-network

  # Node.js Service (for Frontend Development)
  # ターミナルで `npm run dev` を実行するために利用
  node:
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    user: "${UID}:${GID}"
    working_dir: /var/www
    volumes:
      - ./:/var/www
#      - ./node_modules:/var/www/node_modules
    command: npm run dev
    tty: true # コンテナを起動し続けるため
    ports:
      - "5173:5173"
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  db-data: # データを永続化するための名前付きボリューム
