server {
    listen 80;
    server_name taketo-u.net daytrip-atlas.com;

    # 証明書更新のための認証用パス
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    # HTTPからHTTPSへリダイレクト
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name taketo-u.net daytrip-atlas.com;
    root /var/www/public;

    # SSL証明書のパス（取得済みファイル）
    ssl_certificate /etc/letsencrypt/live/taketo-u.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/taketo-u.net/privkey.pem;

    # セキュリティ設定
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # ログ設定
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    index index.php;
    charset utf-8;
    client_max_body_size 20M;

    location ^~ /storage/ {
            alias /var/www/storage/app/public/;
            add_header Cache-Control "public";
        }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPMへの接続設定
    location ~ \.php$ {
        # docker-composeのサービス名が 'php' であると仮定しています
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
