<?php

namespace Database\Seeders\Prefectures;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * 愛知県のクラスターデータをシードする
 *
 * このファイルは scripts/generate_prefecture_seeders.php によって自動生成されました。
 * XMLファイルから抽出したデータがハードコードされています。
 */
class AichiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clusters = [
            0 => [
                'admin_code' => '23201',
                'name' => '愛知県豊橋市',
                'lat' => 34.769199,
                'lon' => 137.391469,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            1 => [
                'admin_code' => '23202',
                'name' => '愛知県岡崎市',
                'lat' => 34.954809,
                'lon' => 137.172999,
                'office_count' => 8,
                'main_office_count' => 1,
            ],
            2 => [
                'admin_code' => '23203',
                'name' => '愛知県一宮市',
                'lat' => 35.304013,
                'lon' => 136.802344,
                'office_count' => 13,
                'main_office_count' => 1,
            ],
            3 => [
                'admin_code' => '23204',
                'name' => '愛知県瀬戸市',
                'lat' => 35.22362,
                'lon' => 137.084117,
                'office_count' => 4,
                'main_office_count' => 1,
            ],
            4 => [
                'admin_code' => '23205',
                'name' => '愛知県半田市',
                'lat' => 34.892626,
                'lon' => 136.93785,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            5 => [
                'admin_code' => '23206',
                'name' => '愛知県春日井市',
                'lat' => 35.247664,
                'lon' => 136.972232,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
            6 => [
                'admin_code' => '23207',
                'name' => '愛知県豊川市',
                'lat' => 34.826784,
                'lon' => 137.375578,
                'office_count' => 5,
                'main_office_count' => 1,
            ],
            7 => [
                'admin_code' => '23208',
                'name' => '愛知県津島市',
                'lat' => 35.17704,
                'lon' => 136.741236,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            8 => [
                'admin_code' => '23209',
                'name' => '愛知県碧南市',
                'lat' => 34.884782,
                'lon' => 136.993362,
                'office_count' => 5,
                'main_office_count' => 1,
            ],
            9 => [
                'admin_code' => '23211',
                'name' => '愛知県豊田市',
                'lat' => 35.082345,
                'lon' => 137.156224,
                'office_count' => 14,
                'main_office_count' => 1,
            ],
            10 => [
                'admin_code' => '23212',
                'name' => '愛知県安城市',
                'lat' => 34.958644,
                'lon' => 137.080297,
                'office_count' => 4,
                'main_office_count' => 1,
            ],
            11 => [
                'admin_code' => '23213',
                'name' => '愛知県西尾市',
                'lat' => 34.862009,
                'lon' => 137.061741,
                'office_count' => 6,
                'main_office_count' => 1,
            ],
            12 => [
                'admin_code' => '23214',
                'name' => '愛知県蒲郡市',
                'lat' => 34.826439,
                'lon' => 137.219653,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            13 => [
                'admin_code' => '23215',
                'name' => '愛知県犬山市',
                'lat' => 35.378641,
                'lon' => 136.944625,
                'office_count' => 5,
                'main_office_count' => 1,
            ],
            14 => [
                'admin_code' => '23216',
                'name' => '愛知県常滑市',
                'lat' => 34.886678,
                'lon' => 136.832375,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            15 => [
                'admin_code' => '23217',
                'name' => '愛知県江南市',
                'lat' => 35.331953,
                'lon' => 136.870453,
                'office_count' => 4,
                'main_office_count' => 1,
            ],
            16 => [
                'admin_code' => '23219',
                'name' => '愛知県小牧市',
                'lat' => 35.291141,
                'lon' => 136.911971,
                'office_count' => 5,
                'main_office_count' => 1,
            ],
            17 => [
                'admin_code' => '23221',
                'name' => '愛知県新城市',
                'lat' => 34.899226,
                'lon' => 137.498504,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            18 => [
                'admin_code' => '23222',
                'name' => '愛知県東海市',
                'lat' => 35.022976,
                'lon' => 136.902229,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            19 => [
                'admin_code' => '23223',
                'name' => '愛知県大府市',
                'lat' => 35.011611,
                'lon' => 136.963868,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            20 => [
                'admin_code' => '23224',
                'name' => '愛知県知多市',
                'lat' => 34.996533,
                'lon' => 136.864755,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            21 => [
                'admin_code' => '23225',
                'name' => '愛知県知立市',
                'lat' => 35.001285,
                'lon' => 137.050843,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
            22 => [
                'admin_code' => '23226',
                'name' => '愛知県尾張旭市',
                'lat' => 35.216568,
                'lon' => 137.035412,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            23 => [
                'admin_code' => '23227',
                'name' => '愛知県高浜市',
                'lat' => 34.92763,
                'lon' => 136.98766,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
            24 => [
                'admin_code' => '23228',
                'name' => '愛知県岩倉市',
                'lat' => 35.279433,
                'lon' => 136.871428,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            25 => [
                'admin_code' => '23229',
                'name' => '愛知県豊明市',
                'lat' => 35.053756,
                'lon' => 137.013124,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
            26 => [
                'admin_code' => '23231',
                'name' => '愛知県田原市',
                'lat' => 34.668972,
                'lon' => 137.26383,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
            27 => [
                'admin_code' => '23232',
                'name' => '愛知県愛西市',
                'lat' => 35.152802,
                'lon' => 136.728217,
                'office_count' => 6,
                'main_office_count' => 1,
            ],
            28 => [
                'admin_code' => '23233',
                'name' => '愛知県清須市',
                'lat' => 35.199848,
                'lon' => 136.852934,
                'office_count' => 4,
                'main_office_count' => 1,
            ],
            29 => [
                'admin_code' => '23234',
                'name' => '愛知県北名古屋市',
                'lat' => 35.245657,
                'lon' => 136.865961,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
            30 => [
                'admin_code' => '23235',
                'name' => '愛知県弥富市',
                'lat' => 35.110118,
                'lon' => 136.72472,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            31 => [
                'admin_code' => '23236',
                'name' => '愛知県みよし市',
                'lat' => 35.089699,
                'lon' => 137.074728,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            32 => [
                'admin_code' => '23237',
                'name' => '愛知県あま市',
                'lat' => 35.200498,
                'lon' => 136.783227,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            33 => [
                'admin_code' => '23302',
                'name' => '愛知県東郷町',
                'lat' => 35.09679,
                'lon' => 137.052623,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            34 => [
                'admin_code' => '23238',
                'name' => '愛知県長久手市',
                'lat' => 35.18412,
                'lon' => 137.048631,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            35 => [
                'admin_code' => '23342',
                'name' => '愛知県豊山町',
                'lat' => 35.250462,
                'lon' => 136.911977,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            36 => [
                'admin_code' => '23361',
                'name' => '愛知県大口町',
                'lat' => 35.332444,
                'lon' => 136.907694,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            37 => [
                'admin_code' => '23362',
                'name' => '愛知県扶桑町',
                'lat' => 35.35914,
                'lon' => 136.913079,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            38 => [
                'admin_code' => '23424',
                'name' => '愛知県大治町',
                'lat' => 35.175089,
                'lon' => 136.8201,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            39 => [
                'admin_code' => '23425',
                'name' => '愛知県蟹江町',
                'lat' => 35.132339,
                'lon' => 136.786679,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            40 => [
                'admin_code' => '23427',
                'name' => '愛知県飛島村',
                'lat' => 35.078804,
                'lon' => 136.791157,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            41 => [
                'admin_code' => '23441',
                'name' => '愛知県阿久比町',
                'lat' => 34.932569,
                'lon' => 136.915512,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            42 => [
                'admin_code' => '23442',
                'name' => '愛知県東浦町',
                'lat' => 34.977139,
                'lon' => 136.965569,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            43 => [
                'admin_code' => '23445',
                'name' => '愛知県南知多町',
                'lat' => 34.715169,
                'lon' => 136.929934,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            44 => [
                'admin_code' => '23446',
                'name' => '愛知県美浜町',
                'lat' => 34.778843,
                'lon' => 136.908251,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            45 => [
                'admin_code' => '23447',
                'name' => '愛知県武豊町',
                'lat' => 34.85097,
                'lon' => 136.914937,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            46 => [
                'admin_code' => '23501',
                'name' => '愛知県幸田町',
                'lat' => 34.864425,
                'lon' => 137.165667,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            47 => [
                'admin_code' => '23561',
                'name' => '愛知県設楽町',
                'lat' => 35.097298,
                'lon' => 137.571225,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
            48 => [
                'admin_code' => '23562',
                'name' => '愛知県東栄町',
                'lat' => 35.07693,
                'lon' => 137.697833,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            49 => [
                'admin_code' => '23563',
                'name' => '愛知県豊根村',
                'lat' => 35.146394,
                'lon' => 137.719871,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
            50 => [
                'admin_code' => '23100',
                'name' => '愛知県名古屋市',
                'lat' => 35.181433,
                'lon' => 136.906421,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
        ];

        $now = Carbon::now();

        foreach ($clusters as $cluster) {
            DB::table('clusters')->insert([
                'uuid' => Str::uuid()->toString(),
                'name' => $cluster['name'],
                'location' => DB::raw("ST_GeogFromText('POINT({$cluster['lon']} {$cluster['lat']})')"),
                'status' => 'published',
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }
}
