<?php

namespace Database\Seeders\Prefectures;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * 東京都のクラスターデータをシードする
 *
 * このファイルは scripts/generate_prefecture_seeders.php によって自動生成されました。
 * XMLファイルから抽出したデータがハードコードされています。
 */
class TokyoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clusters = [
            0 => [
                'admin_code' => '13101',
                'name' => '東京都千代田区',
                'lat' => 35.694003,
                'lon' => 139.753634,
                'office_count' => 7,
                'main_office_count' => 1,
            ],
            1 => [
                'admin_code' => '13102',
                'name' => '東京都中央区',
                'lat' => 35.670587,
                'lon' => 139.772003,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            2 => [
                'admin_code' => '13103',
                'name' => '東京都港区',
                'lat' => 35.658071,
                'lon' => 139.751599,
                'office_count' => 6,
                'main_office_count' => 1,
            ],
            3 => [
                'admin_code' => '13104',
                'name' => '東京都新宿区',
                'lat' => 35.69389,
                'lon' => 139.703463,
                'office_count' => 11,
                'main_office_count' => 1,
            ],
            4 => [
                'admin_code' => '13105',
                'name' => '東京都文京区',
                'lat' => 35.707976,
                'lon' => 139.752473,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            5 => [
                'admin_code' => '13106',
                'name' => '東京都台東区',
                'lat' => 35.712607,
                'lon' => 139.779984,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            6 => [
                'admin_code' => '13107',
                'name' => '東京都墨田区',
                'lat' => 35.710724,
                'lon' => 139.801497,
                'office_count' => 6,
                'main_office_count' => 1,
            ],
            7 => [
                'admin_code' => '13108',
                'name' => '東京都江東区',
                'lat' => 35.672859,
                'lon' => 139.817365,
                'office_count' => 9,
                'main_office_count' => 1,
            ],
            8 => [
                'admin_code' => '13109',
                'name' => '東京都品川区',
                'lat' => 35.609066,
                'lon' => 139.73025,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            9 => [
                'admin_code' => '13111',
                'name' => '東京都大田区',
                'lat' => 35.56126,
                'lon' => 139.715987,
                'office_count' => 19,
                'main_office_count' => 1,
            ],
            10 => [
                'admin_code' => '13112',
                'name' => '東京都世田谷区',
                'lat' => 35.646481,
                'lon' => 139.653208,
                'office_count' => 12,
                'main_office_count' => 1,
            ],
            11 => [
                'admin_code' => '13113',
                'name' => '東京都渋谷区',
                'lat' => 35.663982,
                'lon' => 139.697948,
                'office_count' => 10,
                'main_office_count' => 1,
            ],
            12 => [
                'admin_code' => '13114',
                'name' => '東京都中野区',
                'lat' => 35.707268,
                'lon' => 139.663738,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            13 => [
                'admin_code' => '13115',
                'name' => '東京都杉並区',
                'lat' => 35.699546,
                'lon' => 139.636414,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            14 => [
                'admin_code' => '13116',
                'name' => '東京都豊島区',
                'lat' => 35.732437,
                'lon' => 139.715469,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            15 => [
                'admin_code' => '13117',
                'name' => '東京都北区',
                'lat' => 35.752805,
                'lon' => 139.733657,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            16 => [
                'admin_code' => '13118',
                'name' => '東京都荒川区',
                'lat' => 35.736083,
                'lon' => 139.783372,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            17 => [
                'admin_code' => '13119',
                'name' => '東京都板橋区',
                'lat' => 35.751245,
                'lon' => 139.709246,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
            18 => [
                'admin_code' => '13121',
                'name' => '東京都足立区',
                'lat' => 35.774945,
                'lon' => 139.804584,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            19 => [
                'admin_code' => '13122',
                'name' => '東京都葛飾区',
                'lat' => 35.74343,
                'lon' => 139.847213,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            20 => [
                'admin_code' => '13123',
                'name' => '東京都江戸川区',
                'lat' => 35.706648,
                'lon' => 139.868312,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            21 => [
                'admin_code' => '13201',
                'name' => '東京都八王子市',
                'lat' => 35.66657,
                'lon' => 139.316075,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            22 => [
                'admin_code' => '13202',
                'name' => '東京都立川市',
                'lat' => 35.713981,
                'lon' => 139.407846,
                'office_count' => 5,
                'main_office_count' => 1,
            ],
            23 => [
                'admin_code' => '13203',
                'name' => '東京都武蔵野市',
                'lat' => 35.717837,
                'lon' => 139.565938,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            24 => [
                'admin_code' => '13204',
                'name' => '東京都三鷹市',
                'lat' => 35.683308,
                'lon' => 139.559883,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            25 => [
                'admin_code' => '13205',
                'name' => '東京都青梅市',
                'lat' => 35.788171,
                'lon' => 139.274994,
                'office_count' => 5,
                'main_office_count' => 1,
            ],
            26 => [
                'admin_code' => '13206',
                'name' => '東京都府中市',
                'lat' => 35.668921,
                'lon' => 139.477663,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            27 => [
                'admin_code' => '13207',
                'name' => '東京都昭島市',
                'lat' => 35.705705,
                'lon' => 139.353773,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
            28 => [
                'admin_code' => '13208',
                'name' => '東京都調布市',
                'lat' => 35.650628,
                'lon' => 139.540683,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
            29 => [
                'admin_code' => '13209',
                'name' => '東京都町田市',
                'lat' => 35.546559,
                'lon' => 139.438527,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            30 => [
                'admin_code' => '13211',
                'name' => '東京都小平市',
                'lat' => 35.728496,
                'lon' => 139.477474,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            31 => [
                'admin_code' => '13212',
                'name' => '東京都日野市',
                'lat' => 35.671347,
                'lon' => 139.394981,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            32 => [
                'admin_code' => '13213',
                'name' => '東京都東村山市',
                'lat' => 35.754624,
                'lon' => 139.468484,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            33 => [
                'admin_code' => '13214',
                'name' => '東京都国分寺市',
                'lat' => 35.710943,
                'lon' => 139.462252,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            34 => [
                'admin_code' => '13215',
                'name' => '東京都国立市',
                'lat' => 35.683912,
                'lon' => 139.441366,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            35 => [
                'admin_code' => '13218',
                'name' => '東京都福生市',
                'lat' => 35.738601,
                'lon' => 139.326744,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            36 => [
                'admin_code' => '13219',
                'name' => '東京都狛江市',
                'lat' => 35.634814,
                'lon' => 139.578696,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            37 => [
                'admin_code' => '13221',
                'name' => '東京都清瀬市',
                'lat' => 35.785761,
                'lon' => 139.526422,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            38 => [
                'admin_code' => '13222',
                'name' => '東京都東久留米市',
                'lat' => 35.757992,
                'lon' => 139.529673,
                'office_count' => 4,
                'main_office_count' => 1,
            ],
            39 => [
                'admin_code' => '13223',
                'name' => '東京都武蔵村山市',
                'lat' => 35.754906,
                'lon' => 139.387421,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
            40 => [
                'admin_code' => '13224',
                'name' => '東京都多摩市',
                'lat' => 35.636959,
                'lon' => 139.446366,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            41 => [
                'admin_code' => '13225',
                'name' => '東京都稲城市',
                'lat' => 35.637938,
                'lon' => 139.504603,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            42 => [
                'admin_code' => '13227',
                'name' => '東京都羽村市',
                'lat' => 35.767168,
                'lon' => 139.311042,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            43 => [
                'admin_code' => '13228',
                'name' => '東京都あきる野市',
                'lat' => 35.728959,
                'lon' => 139.294046,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            44 => [
                'admin_code' => '13229',
                'name' => '東京都西東京市',
                'lat' => 35.725499,
                'lon' => 139.538159,
                'office_count' => 4,
                'main_office_count' => 1,
            ],
            45 => [
                'admin_code' => '13303',
                'name' => '東京都瑞穂町',
                'lat' => 35.771989,
                'lon' => 139.354054,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            46 => [
                'admin_code' => '13305',
                'name' => '東京都日の出町',
                'lat' => 35.742115,
                'lon' => 139.257405,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            47 => [
                'admin_code' => '13307',
                'name' => '東京都檜原村',
                'lat' => 35.72684,
                'lon' => 139.148852,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            48 => [
                'admin_code' => '13308',
                'name' => '東京都奥多摩町',
                'lat' => 35.80952,
                'lon' => 139.096214,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
            49 => [
                'admin_code' => '13361',
                'name' => '東京都大島町',
                'lat' => 34.750058,
                'lon' => 139.355619,
                'office_count' => 7,
                'main_office_count' => 1,
            ],
            50 => [
                'admin_code' => '13362',
                'name' => '東京都利島村',
                'lat' => 34.529354,
                'lon' => 139.282584,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            51 => [
                'admin_code' => '13363',
                'name' => '東京都新島村',
                'lat' => 34.377138,
                'lon' => 139.256556,
                'office_count' => 3,
                'main_office_count' => 1,
            ],
            52 => [
                'admin_code' => '13364',
                'name' => '東京都神津島村',
                'lat' => 34.205371,
                'lon' => 139.134426,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            53 => [
                'admin_code' => '13381',
                'name' => '東京都三宅村',
                'lat' => 34.075779,
                'lon' => 139.479747,
                'office_count' => 5,
                'main_office_count' => 1,
            ],
            54 => [
                'admin_code' => '13382',
                'name' => '東京都御蔵島村',
                'lat' => 33.897156,
                'lon' => 139.596009,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            55 => [
                'admin_code' => '13401',
                'name' => '東京都八丈町',
                'lat' => 33.109413,
                'lon' => 139.790927,
                'office_count' => 5,
                'main_office_count' => 1,
            ],
            56 => [
                'admin_code' => '13402',
                'name' => '東京都青ヶ島村',
                'lat' => 32.466537,
                'lon' => 139.763337,
                'office_count' => 1,
                'main_office_count' => 1,
            ],
            57 => [
                'admin_code' => '13421',
                'name' => '東京都小笠原村',
                'lat' => 27.09438,
                'lon' => 142.191904,
                'office_count' => 2,
                'main_office_count' => 1,
            ],
        ];

        $now = Carbon::now();

        foreach ($clusters as $cluster) {
            DB::table('clusters')->insert([
                'uuid' => Str::uuid()->toString(),
                'name' => $cluster['name'],
                'location' => DB::raw("ST_GeogFromText('POINT({$cluster['lon']} {$cluster['lat']})')"),
                'status' => 'published',
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }
    }
}
